[tool.poetry]
name = "sproutaitest"
version = "0.1.0"
description = "Tech test for sprout.ai"
authors = ["Mirko Morandi"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
